from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class RouteSpec:
    method: str
    path: str
    handler_name: str


WEBUI_ROUTES: tuple[RouteSpec, ...] = (
    RouteSpec("GET", "/api/global-config", "api_global_config_get"),
    RouteSpec("POST", "/api/global-config", "api_global_config_post"),
    RouteSpec("GET", "/api/providers", "api_providers_get"),
    RouteSpec("POST", "/api/providers", "api_providers_post"),
    RouteSpec("POST", "/api/providers/probe", "api_providers_probe"),
    RouteSpec("POST", "/api/providers/refresh-models", "api_providers_refresh_models"),
    RouteSpec("GET", "/api/providers/models-dev/{provider_type}", "api_providers_models_dev_get"),
    RouteSpec("GET", "/api/models", "api_available_models_get"),
    RouteSpec("GET", "/api/tokens", "api_tokens_get"),
    RouteSpec("GET", "/api/telemetry", "api_telemetry_get"),
    RouteSpec("GET", "/api/embedding/status", "api_embedding_status"),
    RouteSpec("POST", "/api/embedding/restart", "api_embedding_restart"),
    RouteSpec("GET", "/api/personas", "api_personas_get"),
    RouteSpec("POST", "/api/personas", "api_personas_post"),
    RouteSpec("DELETE", "/api/personas/{name}", "api_personas_delete"),
    RouteSpec("GET", "/api/personas/{name}", "api_persona_get_single"),
    RouteSpec("GET", "/api/personas/{name}/status", "api_persona_status_get"),
    RouteSpec("POST", "/api/personas/{name}/start", "api_persona_start"),
    RouteSpec("POST", "/api/personas/{name}/stop", "api_persona_stop"),
    RouteSpec("POST", "/api/personas/{name}/restart", "api_persona_restart"),
    RouteSpec("GET", "/api/system/logs", "api_system_logs_get"),
    RouteSpec("GET", "/api/personas/{name}/logs", "api_persona_logs_get"),
    RouteSpec("GET", "/api/personas/{name}/persona", "api_persona_get"),
    RouteSpec("POST", "/api/personas/{name}/persona", "api_persona_post"),
    RouteSpec("POST", "/api/personas/{name}/persona/save", "api_persona_post"),
    RouteSpec("GET", "/api/personas/{name}/persona/interview", "api_persona_interview_get"),
    RouteSpec("POST", "/api/personas/{name}/persona/interview", "api_persona_interview"),
    RouteSpec("GET", "/api/personas/{name}/orchestration", "api_orchestration_get"),
    RouteSpec("POST", "/api/personas/{name}/orchestration", "api_orchestration_post"),
    RouteSpec("GET", "/api/personas/{name}/experience", "api_experience_get"),
    RouteSpec("POST", "/api/personas/{name}/experience", "api_experience_post"),
    RouteSpec("GET", "/api/personas/{name}/adapters", "api_adapters_get"),
    RouteSpec("POST", "/api/personas/{name}/adapters", "api_adapters_post"),
    RouteSpec("POST", "/api/personas/{name}/engine/reload", "api_engine_reload"),
    RouteSpec("GET", "/api/personas/{name}/tokens", "api_persona_tokens_get"),
    RouteSpec("GET", "/api/personas/{name}/cognition", "api_persona_cognition_get"),
    RouteSpec("GET", "/api/personas/{name}/cognition/analysis", "api_persona_cognition_analysis_get"),
    RouteSpec("GET", "/api/personas/{name}/diary", "api_persona_diary_get"),
    RouteSpec("GET", "/api/personas/{name}/vector-store-status", "api_persona_vector_store_status_get"),
    RouteSpec("GET", "/api/personas/{name}/users", "api_persona_users_get"),
    RouteSpec("GET", "/api/personas/{name}/users/{user_id}", "api_persona_user_get"),
    RouteSpec("GET", "/api/personas/{name}/glossary", "api_persona_glossary_get"),
    RouteSpec("POST", "/api/personas/{name}/config", "api_config_post"),
    RouteSpec("GET", "/api/personas/{name}/skills", "api_persona_skills_get"),
    RouteSpec("POST", "/api/personas/{name}/skills/{skill_name}/toggle", "api_persona_skill_toggle"),
    RouteSpec("GET", "/api/personas/{name}/skills/{skill_name}/config", "api_persona_skill_config_get"),
    RouteSpec("POST", "/api/personas/{name}/skills/{skill_name}/config", "api_persona_skill_config_post"),
    RouteSpec("GET", "/api/personas/{name}/skill-history", "api_persona_skill_history_get"),
    RouteSpec("GET", "/api/personas/{name}/memory-viz", "api_persona_memory_viz"),
    RouteSpec("GET", "/api/personas/{name}/memory/dashboard", "api_memory_dashboard"),
    RouteSpec("GET", "/api/personas/{name}/memory/evolution", "api_evolution_records"),
    RouteSpec("GET", "/api/personas/{name}/memory/evolution/uncertain", "api_evolution_uncertain"),
    RouteSpec("GET", "/api/personas/{name}/memory/evolution/{record_id}/history", "api_evolution_history"),
    RouteSpec("GET", "/api/personas/{name}/memory/situations", "api_situations_list"),
    RouteSpec("DELETE", "/api/personas/{name}/memory/situations", "api_situations_delete"),
    RouteSpec("GET", "/api/personas/{name}/memory/diary-slices", "api_diary_slices"),
    RouteSpec("DELETE", "/api/personas/{name}/memory/diary-slices", "api_diary_slices_delete"),
    RouteSpec("GET", "/api/personas/{name}/memory/biographies", "api_biography_list_all"),
    RouteSpec("GET", "/api/personas/{name}/memory/biography/{user_id}", "api_biography_view"),
    RouteSpec("GET", "/api/personas/{name}/memory/gaps/{user_id}", "api_knowledge_gaps"),
    RouteSpec("GET", "/api/personas/{name}/conversations", "api_persona_conversation_history_get"),
    RouteSpec("GET", "/api/personas/{name}/biography", "api_persona_biography_list"),
    RouteSpec("GET", "/api/personas/{name}/biography/aliases", "api_persona_biography_alias_index"),
    RouteSpec("POST", "/api/personas/{name}/biography/aliases", "api_persona_biography_alias_index_update"),
    RouteSpec("GET", "/api/personas/{name}/biography/{user_id}", "api_persona_biography_get"),
    RouteSpec("POST", "/api/auth/login", "api_auth_login"),
    RouteSpec("GET", "/api/auth/status", "api_auth_status"),
    RouteSpec("GET", "/api/monitoring/overview", "api_monitoring_overview"),
    RouteSpec("GET", "/api/monitoring/{name}/metrics", "api_monitoring_persona_metrics"),
    RouteSpec("GET", "/api/monitoring/{name}/health", "api_monitoring_health"),
    RouteSpec("POST", "/api/personas/{name}/clone", "api_persona_clone"),
    RouteSpec("GET", "/api/plugins", "api_plugins_get"),
    RouteSpec("GET", "/api/plugins/{plugin_name}", "api_plugin_detail_get"),
    RouteSpec("POST", "/api/plugins/{plugin_name}/toggle", "api_plugin_toggle"),
    RouteSpec("GET", "/api/plugins/{plugin_name}/config", "api_plugin_config_get"),
    RouteSpec("PUT", "/api/plugins/{plugin_name}/config", "api_plugin_config_post"),
    RouteSpec("GET", "/api/plugins/{plugin_name}/settings", "api_plugin_settings_get"),
    RouteSpec("POST", "/api/plugins/{plugin_name}/settings", "api_plugin_settings_post"),
    RouteSpec("POST", "/api/plugins/{plugin_name}/settings/{key}", "api_plugin_setting_post"),
    RouteSpec("DELETE", "/api/plugins/{plugin_name}/settings/{key}", "api_plugin_setting_delete"),
    RouteSpec("POST", "/api/plugins/reload", "api_plugins_reload"),
    RouteSpec("GET", "/api/plugins/monitor_repos", "api_plugin_monitor_repos_get"),
)
