from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class RouteSpec:
    method: str
    path: str
    handler_name: str


WEBUI_ROUTES: tuple[RouteSpec, ...] = (
    # ── 全局 API（无 persona 参数） ──
    RouteSpec("GET", "/api/global-config", "api_global_config_get"),
    RouteSpec("POST", "/api/global-config", "api_global_config_post"),
    RouteSpec("GET", "/api/providers", "api_providers_get"),
    RouteSpec("POST", "/api/providers", "api_providers_post"),
    RouteSpec("POST", "/api/providers/probe", "api_providers_probe"),
    RouteSpec("POST", "/api/providers/refresh-models", "api_providers_refresh_models"),
    RouteSpec("GET", "/api/providers/models-dev/{provider_type}", "api_providers_models_dev_get"),
    RouteSpec("GET", "/api/models", "api_available_models_get"),
    RouteSpec("GET", "/api/tokens", "api_tokens_get"),
    RouteSpec("GET", "/api/telemetry", "api_telemetry_get"),
    RouteSpec("GET", "/api/embedding/status", "api_embedding_status"),
    RouteSpec("POST", "/api/embedding/restart", "api_embedding_restart"),
    RouteSpec("GET", "/api/system/logs", "api_system_logs_get"),
    RouteSpec("POST", "/api/auth/login", "api_auth_login"),
    RouteSpec("GET", "/api/auth/status", "api_auth_status"),
    RouteSpec("GET", "/api/monitoring/overview", "api_monitoring_overview"),
    RouteSpec("GET", "/api/monitoring/metrics", "api_monitoring_persona_metrics"),
    RouteSpec("GET", "/api/monitoring/health", "api_monitoring_health"),
    RouteSpec("POST", "/api/shutdown", "api_shutdown"),
    # ── 人格管理 API ──
    RouteSpec("GET", "/api/personas", "api_personas_list"),
    RouteSpec("POST", "/api/personas", "api_persona_create"),
    RouteSpec("GET", "/api/personas/active", "api_persona_active_get"),
    RouteSpec("POST", "/api/personas/{name}/activate", "api_persona_activate"),
    RouteSpec("DELETE", "/api/personas/{name}", "api_persona_delete"),
    RouteSpec("POST", "/api/persona/start", "api_persona_start"),
    RouteSpec("POST", "/api/persona/stop", "api_persona_stop"),
    RouteSpec("GET", "/api/persona/status", "api_persona_status"),
    # ── 数据同步 API（供助手端调用） ──
    RouteSpec("GET", "/api/data/snapshot", "api_data_snapshot_get"),
    RouteSpec("POST", "/api/data/snapshot", "api_data_snapshot_post"),
    RouteSpec("POST", "/api/data/messages", "api_data_messages_post"),
    RouteSpec("POST", "/api/data/users", "api_data_users_post"),
    RouteSpec("POST", "/api/data/glossary", "api_data_glossary_post"),
    RouteSpec("POST", "/api/data/batch", "api_data_batch_post"),
    # ── 单人格 API（/api/persona/*） ──
    RouteSpec("GET", "/api/persona", "api_persona_get_single"),
    RouteSpec("GET", "/api/persona/status", "api_persona_status_get"),
    RouteSpec("GET", "/api/persona/logs", "api_persona_logs_get"),
    RouteSpec("GET", "/api/persona/persona", "api_persona_get"),
    RouteSpec("POST", "/api/persona/persona", "api_persona_post"),
    RouteSpec("POST", "/api/persona/persona/save", "api_persona_post"),
    RouteSpec("GET", "/api/persona/persona/interview", "api_persona_interview_get"),
    RouteSpec("POST", "/api/persona/persona/interview", "api_persona_interview"),
    RouteSpec("GET", "/api/persona/orchestration", "api_orchestration_get"),
    RouteSpec("POST", "/api/persona/orchestration", "api_orchestration_post"),
    RouteSpec("GET", "/api/persona/task-params", "api_task_params_get"),
    RouteSpec("POST", "/api/persona/task-params", "api_task_params_post"),
    RouteSpec("GET", "/api/persona/experience", "api_experience_get"),
    RouteSpec("POST", "/api/persona/experience", "api_experience_post"),
    RouteSpec("GET", "/api/persona/adapters", "api_adapters_get"),
    RouteSpec("POST", "/api/persona/adapters", "api_adapters_post"),
    RouteSpec("POST", "/api/persona/engine/reload", "api_engine_reload"),
    RouteSpec("GET", "/api/persona/tokens", "api_persona_tokens_get"),
    RouteSpec("GET", "/api/persona/cognition", "api_persona_cognition_get"),
    RouteSpec("GET", "/api/persona/cognition/analysis", "api_persona_cognition_analysis_get"),
    RouteSpec("GET", "/api/persona/diary", "api_persona_diary_get"),
    RouteSpec("GET", "/api/persona/vector-store-status", "api_persona_vector_store_status_get"),
    RouteSpec("GET", "/api/persona/users", "api_persona_users_get"),
    RouteSpec("GET", "/api/persona/users/{user_id}", "api_persona_user_get"),
    RouteSpec("GET", "/api/persona/glossary", "api_persona_glossary_get"),
    RouteSpec("POST", "/api/persona/config", "api_config_post"),
    RouteSpec("GET", "/api/persona/skills", "api_persona_skills_get"),
    RouteSpec("POST", "/api/persona/skills/{skill_name}/toggle", "api_persona_skill_toggle"),
    RouteSpec("GET", "/api/persona/skills/{skill_name}/config", "api_persona_skill_config_get"),
    RouteSpec("POST", "/api/persona/skills/{skill_name}/config", "api_persona_skill_config_post"),
    RouteSpec("GET", "/api/persona/skill-history", "api_persona_skill_history_get"),
    RouteSpec("GET", "/api/persona/memory-viz", "api_persona_memory_viz"),
    RouteSpec("GET", "/api/persona/memory/dashboard", "api_memory_dashboard"),
    RouteSpec("GET", "/api/persona/memory/evolution", "api_evolution_records"),
    RouteSpec("GET", "/api/persona/memory/evolution/uncertain", "api_evolution_uncertain"),
    RouteSpec(
        "GET",
        "/api/persona/memory/evolution/{record_id}/history",
        "api_evolution_history",
    ),
    RouteSpec("GET", "/api/persona/memory/biographies", "api_biography_list_all"),
    RouteSpec("GET", "/api/persona/memory/biography/{user_id}", "api_biography_view"),
    RouteSpec("GET", "/api/persona/memory/gaps/{user_id}", "api_knowledge_gaps"),
    RouteSpec("GET", "/api/persona/conversations", "api_persona_conversation_history_get"),
    RouteSpec("GET", "/api/persona/biography", "api_persona_biography_list"),
    RouteSpec("GET", "/api/persona/biography/aliases", "api_persona_biography_alias_index"),
    RouteSpec("POST", "/api/persona/biography/aliases", "api_persona_biography_alias_index_update"),
    RouteSpec("GET", "/api/persona/biography/{user_id}", "api_persona_biography_get"),
    # ── 插件 API（全局） ──
    RouteSpec("GET", "/api/plugins", "api_plugins_get"),
    RouteSpec("GET", "/api/plugins/{plugin_name}", "api_plugin_detail_get"),
    RouteSpec("POST", "/api/plugins/{plugin_name}/toggle", "api_plugin_toggle"),
    RouteSpec("GET", "/api/plugins/{plugin_name}/config", "api_plugin_config_get"),
    RouteSpec("PUT", "/api/plugins/{plugin_name}/config", "api_plugin_config_post"),
    RouteSpec("GET", "/api/plugins/{plugin_name}/settings", "api_plugin_settings_get"),
    RouteSpec("POST", "/api/plugins/{plugin_name}/settings", "api_plugin_settings_post"),
    RouteSpec("POST", "/api/plugins/{plugin_name}/settings/{key}", "api_plugin_setting_post"),
    RouteSpec("DELETE", "/api/plugins/{plugin_name}/settings/{key}", "api_plugin_setting_delete"),
    RouteSpec("POST", "/api/plugins/reload", "api_plugins_reload"),
    RouteSpec("GET", "/api/plugins/monitor_repos", "api_plugin_monitor_repos_get"),
)
