from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class RouteSpec:
    method: str
    path: str
    handler_name: str


WEBUI_ROUTES: tuple[RouteSpec, ...] = (
    # ── 全局 API（无 persona 参数） ──
    RouteSpec("GET", "/api/global-config", "api_global_config_get"),
    RouteSpec("POST", "/api/global-config", "api_global_config_post"),
    RouteSpec("GET", "/api/models", "api_available_models_get"),
    RouteSpec("GET", "/api/amkr/status", "api_amkr_status_get"),
    RouteSpec("GET", "/api/amkr/panel", "api_amkr_panel_get"),
    RouteSpec("POST", "/api/amkr/register", "api_amkr_register_post"),
    RouteSpec("POST", "/api/amkr/rotate-inference-key", "api_amkr_rotate_inference_key_post"),
    RouteSpec("GET", "/api/tokens", "api_tokens_get"),
    RouteSpec("GET", "/api/telemetry", "api_telemetry_get"),
    RouteSpec("GET", "/api/embedding/status", "api_embedding_status"),
    RouteSpec("POST", "/api/embedding/rebuild", "api_embedding_rebuild"),
    RouteSpec("GET", "/api/system/logs", "api_system_logs_get"),
    RouteSpec("POST", "/api/auth/login", "api_auth_login"),
    RouteSpec("GET", "/api/auth/status", "api_auth_status"),
    RouteSpec("GET", "/api/monitoring/overview", "api_monitoring_overview"),
    RouteSpec("GET", "/api/monitoring/metrics", "api_monitoring_persona_metrics"),
    RouteSpec("GET", "/api/monitoring/health", "api_monitoring_health"),
    RouteSpec("GET", "/api/dispatcher/overview", "api_dispatcher_overview"),
    RouteSpec("POST", "/api/shutdown", "api_shutdown"),
    # ── 人格管理 API ──
    RouteSpec("GET", "/api/personas", "api_personas_list"),
    RouteSpec("POST", "/api/personas", "api_persona_create"),
    RouteSpec("GET", "/api/personas/active", "api_persona_active_get"),
    RouteSpec("POST", "/api/personas/{name}/activate", "api_persona_activate"),
    RouteSpec("POST", "/api/personas/{name}/start", "api_persona_named_start"),
    RouteSpec("POST", "/api/personas/{name}/stop", "api_persona_named_stop"),
    RouteSpec("GET", "/api/personas/{name}/status", "api_persona_named_status"),
    RouteSpec("DELETE", "/api/personas/{name}", "api_persona_delete"),
    RouteSpec("POST", "/api/persona/start", "api_persona_start"),
    RouteSpec("POST", "/api/persona/stop", "api_persona_stop"),
    RouteSpec("GET", "/api/persona/status", "api_persona_status"),
    # ── 单人格 API（/api/persona/*） ──
    RouteSpec("GET", "/api/persona", "api_persona_get_single"),
    RouteSpec("GET", "/api/persona/logs", "api_persona_logs_get"),
    RouteSpec("GET", "/api/persona/persona", "api_persona_get"),
    RouteSpec("POST", "/api/persona/persona", "api_persona_post"),
    RouteSpec("POST", "/api/persona/persona/save", "api_persona_post"),
    RouteSpec("GET", "/api/persona/experience", "api_experience_get"),
    RouteSpec("POST", "/api/persona/experience", "api_experience_post"),
    RouteSpec("GET", "/api/persona/adapters", "api_adapters_get"),
    RouteSpec("POST", "/api/persona/adapters", "api_adapters_post"),
    RouteSpec("POST", "/api/persona/engine/reload", "api_engine_reload"),
    RouteSpec("GET", "/api/persona/tokens", "api_persona_tokens_get"),
    RouteSpec("GET", "/api/persona/cognition", "api_persona_cognition_get"),
    RouteSpec("GET", "/api/persona/cognition/analysis", "api_persona_cognition_analysis_get"),
    RouteSpec("GET", "/api/persona/diary", "api_persona_diary_get"),
    RouteSpec("POST", "/api/persona/diary", "api_persona_diary_post"),
    RouteSpec("PUT", "/api/persona/diary/{entry_id}", "api_persona_diary_put"),
    RouteSpec("DELETE", "/api/persona/diary/{entry_id}", "api_persona_diary_delete"),
    RouteSpec("GET", "/api/persona/vector-store-status", "api_persona_vector_store_status_get"),
    RouteSpec("GET", "/api/persona/memory-units", "api_persona_memory_units_get"),
    RouteSpec("POST", "/api/persona/memory-units", "api_persona_memory_units_post"),
    RouteSpec("PUT", "/api/persona/memory-units/{unit_id}", "api_persona_memory_unit_put"),
    RouteSpec("DELETE", "/api/persona/memory-units/{unit_id}", "api_persona_memory_unit_delete"),
    RouteSpec("POST", "/api/persona/memory-units/dedupe/scan", "api_persona_memory_dedupe_scan"),
    RouteSpec("GET", "/api/persona/memory-units/dedupe/status", "api_persona_memory_dedupe_status"),
    RouteSpec("POST", "/api/persona/memory-units/dedupe/apply", "api_persona_memory_dedupe_apply"),
    RouteSpec("GET", "/api/persona/memory-units/dedupe/report", "api_persona_memory_dedupe_report"),
    RouteSpec("POST", "/api/persona/config", "api_config_post"),
    RouteSpec("GET", "/api/persona/tools", "api_persona_tools_get"),
    RouteSpec("POST", "/api/persona/tools/{tool_name}/toggle", "api_persona_tool_toggle"),
    RouteSpec("GET", "/api/persona/tools/{tool_name}/config", "api_persona_tool_config_get"),
    RouteSpec("POST", "/api/persona/tools/{tool_name}/config", "api_persona_tool_config_post"),
    RouteSpec("GET", "/api/persona/tool-history", "api_persona_tool_history_get"),
    RouteSpec("GET", "/api/persona/mcp", "api_persona_mcp_get"),
    RouteSpec("POST", "/api/persona/mcp", "api_persona_mcp_post"),
    RouteSpec("GET", "/api/persona/memory-viz", "api_persona_memory_viz"),
    RouteSpec("GET", "/api/persona/autonomy", "api_persona_autonomy_get"),
    RouteSpec("GET", "/api/persona/work-mode", "api_persona_work_mode_get"),
    RouteSpec("GET", "/api/persona/conversations", "api_persona_conversation_history_get"),
    RouteSpec("DELETE", "/api/persona/conversations", "api_persona_conversation_history_delete"),
    # ── 插件 API（全局） ──
    RouteSpec("GET", "/api/plugins", "api_plugins_get"),
    RouteSpec("GET", "/api/plugins/{plugin_name}", "api_plugin_detail_get"),
    RouteSpec("POST", "/api/plugins/{plugin_name}/toggle", "api_plugin_toggle"),
    RouteSpec("GET", "/api/plugins/{plugin_name}/config", "api_plugin_config_get"),
    RouteSpec("PUT", "/api/plugins/{plugin_name}/config", "api_plugin_config_post"),
    RouteSpec("GET", "/api/plugins/{plugin_name}/settings", "api_plugin_settings_get"),
    RouteSpec("POST", "/api/plugins/{plugin_name}/settings", "api_plugin_settings_post"),
    RouteSpec("POST", "/api/plugins/{plugin_name}/settings/{key}", "api_plugin_setting_post"),
    RouteSpec("DELETE", "/api/plugins/{plugin_name}/settings/{key}", "api_plugin_setting_delete"),
    RouteSpec("POST", "/api/plugins/reload", "api_plugins_reload"),
)
